### ISSUE TITLE
new forms cannot load previous values from other forms

### ISSUE THREAD

**Issue by raihan-mpower** [OpenSRP/opensrp-client#118]
I have added the new form technology in the following branch
https://github.com/OpenSRP/opensrp-client/tree/mcare-bangladesh-module-newforms
and currently we have deployed with the old forms from the following branch
https://github.com/OpenSRP/opensrp-client/tree/mcare-bangladesh-module
The issue in the new forms branch is that it cannot preload values from previous forms are not showing up when we load the census form. 
I am also attaching my current form definition and the db file where you can take a look at form submissions.
In the db file the last two census enrollment submissions are using the new form technology. The other ones are all using the old forms.

[plaintextnewforms.db.zip](https://github.com/OpenSRP/opensrp-client/files/60393/plaintextnewforms.db.zip)

also i have attached my form definition for census enrollment form
[form_definition.json.zip](https://github.com/OpenSRP/opensrp-client/files/60394/form_definition.json.zip)

Also you can take look at two different form submissions using old and new forms
[formsubmissions.zip](https://github.com/OpenSRP/opensrp-client/files/60395/formsubmissions.zip)

**Comment by raihan-mpower** [comment]
@koros  can you take a look at this issue

**Comment by koros** [comment]
@raihan-mpower yeah sure, i'll start working on it next. will update you once i make progress probably by tomorrow. Thanks

**Comment by koros** [comment]
@raihan-mpower i have committed some changes, test on your end and let me know if everything is fine, actually the issue had already been fixed in this branch https://github.com/OpenSRP/opensrp-client/tree/mcare-bangladesh-module_enhanced_form

**Comment by raihan-mpower** [comment]
@koros  i am still getting error when i submit a form. The relational id of entities are not being recorded properly. I tried with the latest build. Am i missing something?

**Comment by koros** [comment]
@raihan-mpower please give me the account you were using and steps to reproduce it

**Comment by raihan-mpower** [comment]
username : demosrp
password: Demosrp@123

url ; 27.147.129.50:9979

**Comment by koros** [comment]
Hi Raihan still looking at this issue, I have seen what's going on though
so I'll commit a fix tomorrow, thanks

**Comment by raihan-mpower** [comment]
@koros i fixed this issue using form utils from @dimasciput 's branch of indonesia-faster-form.............but the problem now occurs in a different ocassion. In my elco register the form's save button is not working. If i press back then it gets saved but the form handler is not being called. 
Steps to reproduce the issue-
register a new household with an elco
in the elco register the psrf part will show yellow
click and go to the form
the form's save button is not working

**Comment by raihan-mpower** [comment]
i am referring to this latest commit https://github.com/OpenSRP/opensrp-client/commit/094b255fee8a1a4f5deaca55cf888e44d09cb9ad

**Comment by koros** [comment]
Hi @raihan-mpower alright cool, let me check it out

**Comment by koros** [comment]
@raihan-mpower can we close this now?
