### ISSUE TITLE
Change start and endtime on form-submissions to match OpenMRS date format

### ISSUE THREAD

**Issue by koros** [OpenSRP/opensrp-client#146]
Currently the start and endtime uses format "2015-09-21T11:41:36.000+06:00" while OpenMRS accepts: 2015-09-21 11:41:36

**Comment by raihan-mpower** [comment]
has been fixed

**Comment by sohelsarder** [comment]
We found another case of date formating issues can you please check why this is not resolved by earlier fixation. Please check /find a way so that every fields with date time go through similar  formation.

ANC/BNF Form field

"Field name": "FWEDD",
"Received format": Wed, 31 Aug 2016 22:45:00 GMT          
"Expected format": 2016-10-31 22:45:00

Form sample:
https://docs.google.com/spreadsheets/d/1aV5_NNttWXSM1-S3lZVoqySoPxKZeSr133wkJLgEsyk/edit#gid=522437979

**Comment by cagulas** [comment]
dateTime submitted in Enketo form on Ona shows up like this:

![screen shot 2016-02-24 at 3 55 55 pm](https://cloud.githubusercontent.com/assets/3488986/13285960/3645c61e-db0f-11e5-9da4-fe852bde89c7.png)

@koros can you look at this?

**Comment by koros** [comment]
@cagulas thanks will look into it, i wonder if we can enforce the formatting on all dates since, the options right now is we put the fix for this particular field but if the name changes in future then the fix needs to be reviewed. or we can put an umbrella fix that converts any date fields to the OpenMRS format

**Comment by sohelsarder** [comment]
Do you have a way to know the data type of each field? which one is string or date or everything to you know is a data inside a xml elements. if you know the field data type then every date field should go through this formatting process.

**Comment by koros** [comment]
@sohelsarder we can use a regex to match a date field but that could turn nasty if a random input matches, so we can add another field in the form definition to denote that a field that requires translation

**Comment by koros** [comment]
@sohelsarder please give me an account i can use to test this issue, from what i can see seems the form  that has this field is birthnotificationpregnancystatusfollowup form, please provide an account i can use to access this form.

**Comment by koros** [comment]
Fix committed will test further tomorrow @raihan-mpower can also look at it in the meantime

**Comment by sohelsarder** [comment]
Hey koros did find that  url ? this you can use for check  27.147.129.61:9979

**Comment by koros** [comment]
thanks @sohelsarder is there a particular account with some data i can use

For the fix i added a type and formatting options to the form definition 
``` javascript
{
        "name": "FWEDD",
        "bind": "/model/instance/BirthNotificationPregnancyStatusFollowUp/FWEDD",
        "type": "date",
        "current_format": "EEE, dd MMM yyyy HH:mm:ss z",
        "required_format": "yyyy-MM-dd HH:mm:ss"
},
```

so in future if we need to format another item e.g a float value say to 2 decimal places we can use the same principal. So the only thing we need to watch is when loading back the values to the form e.g for an edit operation then we should probably convert back the date value, for example, to the original format.

**Comment by sohelsarder** [comment]
You might get some data against following account,  user:demosrp,pw:Demosrp@123; user:opensrp, pw:Opensrp@123

**Comment by koros** [comment]
ok cool thanks

**Comment by koros** [comment]
@sohelsarder confirm if the issue is fixed
