### ISSUE TITLE
UI updates to Woman Register in vaccinator apk

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#183]
![screenshot_2016-04-08-14-40-49](https://cloud.githubusercontent.com/assets/3488986/14380678/82dca4ec-fd89-11e5-902c-e730423bcbc0.png)

**Comment by cagulas** [comment]
Also:

![screenshot_2016-04-08-15-04-24](https://cloud.githubusercontent.com/assets/3488986/14380915/1dd1fc4e-fd8b-11e5-8893-bdd16e5a79cc.png)

**Comment by maimoonak** [comment]
Resolved all (release 1.0.1b shared) except pixelated image issue ( #122  ).

- QR code image changed and now icon is bold and visible lines giving it bigger look.
- Red is D13f3f. Not sure why it looks so sharp..

![screenshot_2016-04-08-21-47-59](https://cloud.githubusercontent.com/assets/4829880/14416465/b0683dea-ffc3-11e5-8b5c-751dafe3dbdc.png)

![screenshot_2016-04-08-22-07-42](https://cloud.githubusercontent.com/assets/4829880/14416447/9278b21a-ffc3-11e5-9e9f-c14ae3ba110d.png)

**Comment by cagulas** [comment]
Looks amazing.  New QR code icon is great.

**Comment by cagulas** [comment]
One last tiny thing.  Please make "Today:" in the top row (underneath search bar) not bold.  Similar to "Sorted By:"

**Comment by cagulas** [comment]
@maimoonak please see last comment above. This issue can be closed afterwards.

**Comment by maimoonak** [comment]
Resolved all issues in opensrp-vaccinator-1.2.0

**Comment by cagulas** [comment]
Looks good, but you missed my last comment about removing the space between TT and dose number in NEXT VACCINE DUE column, so TT3 instead of TT 3.

**Comment by maimoonak** [comment]
Oh.. Would resolve in next release.

**Comment by cagulas** [comment]
👍
